### PR TITLE
Use `trybuild` to do compile-fail/pass tests (and fix some minor bugs)

### LINKED ISSUE #55: Add proper compile-fail tests
We already have compile-fail tests, but they in fact only check if compilation indeed fails. It does not check the error message at all. This is pretty unfortunate, because any other random failure can make the test pass. 

See [this PR](https://github.com/auto-impl-rs/auto_impl/pull/17) for discussion on how one would do that. We probably want to use a crate that does it for us, but it's not clear which one.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Thanks again @CreepySkeleton for mentioning `trybuild`.

I'm not 100% happy with the crate:
- It doesn't use an own test harness and it's not possible to filter for specific tests (I think)
- One has to add a `main` function to every single test

But, it works easily and it compares the stderr which is something I wanted for a long time. And it's not super old as `compiletest-rs`. So I think it's a good idea to make this change, even if the crate is not perfect.

Fixes #55 

---

Due to using proper compile-fail testing now, I noticed two bugs actually. 
- Our hack in `diag.rs` uses a thread local variable containing a `Vec<_>`. If our macro exits when the vector still contains elements, the Rust compiler panics. Not just that, it tries to panic but cannot, leading to a "fatal runtime error" and an abort. Uhg. I should probably create an official issue, though I think using thread locals was never officially allowed in proc macros. Workaround: just clear the vector before we are done.
- We didn't check for `#[auto_impl(...)]` attributes on trait items other than methods. That's fixed now.

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
>     * Our hack in `diag.rs` uses a thread local variable containing a `Vec<_>`. If our macro exits when the vector still contains elements, the Rust compiler panics. Not just that, it tries to panic but cannot, leading to a "fatal runtime error" and an abort. Uhg. I should probably create an official issue, though I think using thread locals was never officially allowed in proc macros. Workaround: just clear the vector before we are done.

Yep, I had to yank one version of my crate due to it :laughing:

File: src/diag.rs [hunk 1]
```diff
@@ -150,7 +150,18 @@ thread_local! {
...
+        let out = toks.borrow().iter().cloned().collect();
+
+        // We are clearing the vector here (and dropping all its elements) so
+        // that it does not need to do that ... at some other point. It's
+        // unclear when exactly the thread local variable is dropped. But
+        // currently, if the vector still has elements when our macro is done,
+        // we cause a fatal runtime error inside `rustc`. That's bad.
+        toks.borrow_mut().clear();
+
+        out
```
Comment (CreepySkeleton) [inline src/diag.rs]: Perhaps `std::mem::replace(toks.borrow_mut(), vec![])` would be more clear here

File: src/attr.rs [hunk 2]
```diff
@@ -19,8 +19,24 @@ use crate::{
...
-        fn visit_trait_item_method_mut(&mut self, m: &mut TraitItemMethod) {
-            m.attrs.retain(|a| !is_our_attr(a));
+        fn visit_trait_item_mut(&mut self, item: &mut TraitItem) {
+            let item_span = item.span();
+            let (attrs, is_method) = match item {
+                TraitItem::Method(m) => (&mut m.attrs, true),
+                TraitItem::Const(c) => (&mut c.attrs, false),
+                TraitItem::Type(t) => (&mut t.attrs, false),
+                TraitItem::Macro(m) => (&mut m.attrs, false),
+                _ => panic!("encountered unexpected `TraitItem`, cannot handle that, sorry!"),
```
Comment (CreepySkeleton) [inline src/attr.rs]: Guess what will happen if this panic occurs after you emitted an error?

**Comment by CreepySkeleton** [comment]
And also there's a downside in `trybuild` - it officially supports only rustc +1.36, but [there's a workaround](https://github.com/dtolnay/trybuild/issues/39)

**Comment by KodrAus** [comment]
> And also there's a downside in trybuild - it officially supports only rustc +1.36, but there's a workaround

Bumping our MSRV is something I’m comfortable with :+1:

File: src/attr.rs (hunk 2 above)
Comment (LukasKalbertodt) [reply src/attr.rs]: Nice catch! However, it is clear that the error handling has to change in some way. Either by using your crate or in another way. But that's not something this PR will fix -- I just applied fixes so that nothing immediately breaks. In short: your comment will be addressed in some future PR.

**Comment by LukasKalbertodt** [comment]
Regarding MSRV: this is a `dev-dependency`, right? So users of this crate do not need to worry about it at all. The newer Rust version is just required for testing.

**Comment by LukasKalbertodt** [comment]
Oh, meh. So now we run into problems where stable/beta/nightly might have different error messages. So our `stderr` files need to target one of those three?

**Comment by CreepySkeleton** [comment]
@LukasKalbertodt should I base my PR on top of this one?

**Comment by LukasKalbertodt** [comment]
@CreepySkeleton Yeah, I guess that's a good idea.
